# Generated by Django 5.2.17 on 2026-09-14 17:38

import cinema.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('synopsis', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField(help_text='Full movie runtime in minutes; playback is trailers only.')),
                ('age_rating', models.CharField(default='PG-13', max_length=12)),
                ('director', models.CharField(max_length=120)),
                ('cast', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('language', models.CharField(default='English', max_length=80)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('backdrop', models.ImageField(blank=True, upload_to='backdrops/')),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('trailer', models.FileField(blank=True, help_text='Upload a trailer only, MP4 or WebM, maximum 200 MB. No full movies.', upload_to='trailers/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm']), cinema.models.trailer_size])),
                ('youtube_id', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{11}$', 'Enter the 11-character YouTube video ID.')])),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='cinema.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cinema.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='one_rating_per_user'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 10)), name='rating_range')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='cinema.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='one_save_per_user')],
            },
        ),
    ]
